config/routes.rb
Rails.application.routes.draw do
  resources :destinations, only: [:index, :show] do 
    resources :hacks, shallow: true do
      resources :comments, shallow: true
      resources :likes, shallow: true
    end  
  end
  resources :users, only: [:show, :edit, :update, :destroy] do
    resources :follows, shallow: true
  end
  resources :sessions, only: [:new, :create, :destroy]

  get '/signup', to: 'users#new', as: 'signup'
  post '/signup', to: 'users#create', as: 'users'
  get '/login', to: 'sessions#new', as: 'login'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  get '/search-results', to: 'search#search' 
  root 'welcome#welcome'

end

app/models/hack.rb
class Hack < ApplicationRecord
  belongs_to :user
  belongs_to :destination
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  validates :title, presence: true
  validates :content, presence: true
  

  def category_hacks(cat)
    Hack.where(category: cat)
  end
end

app/controllers/hacks_controller.rb
class HacksController < ApplicationController
    before_action :find_hack, only: [:show, :edit, :update, :destroy]
    before_action :categories, only: [:new, :edit]
    before_action :require_login, only: [:new, :create, :edit, :update, :destroy]


  def index
    @destination = Destination.find(params[:destination_id])
    @category = params[:cat]
  end

  def show
    @comment = Comment.new
    if current_user
      @user = User.find(current_user.id)
    end
  end


  def new
    
    @hack = Hack.new
    @destination = Destination.find(params[:destination_id])
    @dest_city = @destination.city
    @user = User.find(session[:user_id])
  end

  def create
    @hack = Hack.create(hack_params)   
    if @hack.valid?
      redirect_to hack_path(id: @hack)
    else
      flash[:errors] = @hack.errors.full_messages
      redirect_to new_destination_hack_path(params[:destination_id]) 
    end
  end

  def edit
    @dest_city = @hack.destination.city
    @user = User.find(session[:user_id])
    
  end

  def update
    @hack.update(hack_params)
    if @hack.valid?
      redirect_to hack_path(id: @hack)
    else
      flash[:errors] = @hack.errors.full_messages
      redirect_to edit_hack_path
    end 
  end

  def destroy
    @hack.destroy
    redirect_to destinations_path
  end

  private

  def find_hack
    @hack = Hack.find(params[:id])
  end

  def hack_params
    params.require(:hack).permit(:category, :title, :content, :user_id, :destination_id)
  end

  def categories
    @categories = ["Transportation", "Dining", "Nightlife", "Cultural", "Adventure", "Rewards/Points"]
  end

end

app/helpers/hacks_helper.rb
module HacksHelper
end

app/views/hacks/_form.html.erb
<% if flash[:errors] %>
  <% flash[:errors].each do |error| %>
    <%= error %>
  <% end %>
<% end %>

<h3><%= "#{@dest_city} Hack" %></h3>
<br>
<%= form_for [@destination, @hack] do |f| %>
    <div>
      <%= f.label :category %>
      <%= f.select(:category, @categories) %>
    </div>
      <div>
      <%= f.label :title %>
      <%= f.text_field :title %>
    </div>
    <div>
      <%= f.label :content %>
      <%= f.text_area :content %>
    </div>
    <div>
      <%= f.hidden_field :user_id, :value => @user.id %>
      <% if !@hack.id %>
        <%= f.hidden_field :destination_id, :value => @destination.id %>
      <% end %>
    </div>
      
    <%= f.submit class: "btn btn-outline-success btn-sm"%>
  <% end %>

app/views/hacks/edit.html.erb
<%= render 'form' %>

<%= button_to "Delete Hack", @hack, :method => :delete, class: "btn btn-outline-danger btn-sm" %>

app/views/hacks/index.html.erb
<% if @category %>
    <h3><%= @destination.city %> <%= @category %> Hacks</h3>

    
    <% @destination.category_hacks(@category).each do |hack| %>
        <p><%= link_to hack.title, hack %>, Submitted by <%= hack.user.name %></p>    
    <% end %>

<% else %>
    
    <h3><%= @destination.city %> Hacks</h3>

    <h4>Adventure</h4>
    <% @destination.category_hacks("Adventure").each do |hack| %>
        <p><%= link_to hack.title, hack %>, Submitted by <%= hack.user.name %></p>    
    <% end %>
    
    <h4>Cultural</h4>
    <% @destination.category_hacks("Cultural").each do |hack| %>
        <p><%= link_to hack.title, hack %>, Submitted by <%= hack.user.name %></p>
    <% end %>

    <h4>Dining</h4>
    <% @destination.category_hacks("Dining").each do |hack| %>
        <p><%= link_to hack.title, hack %>, Submitted by <%= hack.user.name %></p>
    <% end %>

    <h4>Nightlife</h4>
    <% @destination.category_hacks("Nightlife").each do |hack| %>
        <p><%= link_to hack.title, hack %>, Submitted by <%= hack.user.name %></p>
    <% end %>

    <h4>Rewards/Points</h4>
    <% @destination.category_hacks("Rewards/Points").each do |hack| %>
        <p><%= link_to hack.title, hack %>, Submitted by <%= hack.user.name %></p>
    <% end %>

    <h4>Transportation</h4>
    <% @destination.category_hacks("Transportation").each do |hack| %>
        <p><%= link_to hack.title, hack %>, Submitted by <%= hack.user.name %></p>
    <% end %>

<% end %>

app/views/hacks/new.html.erb
<%= render 'form' %>

app/views/hacks/show.html.erb
<h1><%= @hack.title %></h1>
<h4>Hacker: <%= link_to @hack.user.name, @hack.user %></h4>
<h4>Destination: <%= link_to @hack.destination.str_addr_fields, destination_path(@hack.destination) %></h4>
<h5>Category: <%= @hack.category %></h5>
<h6>Date: <%= @hack.created_at.strftime("%m/%d/%Y") %></h6>
<br>
<%= @hack.content %>
<br>
<br>
<% if logged_in? %> 
  <%= @hack.likes.count %> <%= (@hack.likes.count) == 1 ? 'Like' : 'Likes'%>
  <% pre_like = @hack.likes.find_by(user_id: current_user.id) %>
  <% if pre_like %>
    <%= button_to 'Unlike', like_path(@hack, pre_like), method: :delete, params: {:like => {:user_id => current_user.id, :hack_id => @hack.id}}, class: "btn btn-danger btn-sm" %>
  <% else %>
    <%= button_to 'Like', hack_likes_path(@hack), method: :post, params: {:like => {:user_id => current_user.id, :hack_id => @hack.id}}, class: "btn btn-primary btn-sm" %>
  <% end %>
<% end %>

<br>

<% if current_user == @hack.user %>
    <%= button_to "Edit Hack", edit_hack_path, :method => :get, class: "btn btn-outline-primary btn-sm" %>
<% end %>



<br>
<br>
<h4>Comments</h4>
<% @hack.comments.each do |comment| %>
    <%= comment.content %>
    <br>
    <b><%= comment.user.username %></b>
    <br>
    <% if comment.user == current_user %>
        <%= button_to "Delete Comment", comment, :method => :delete, class: "btn btn-outline-danger btn-sm" %>
    <% end %>
    <br>
<% end %>
<br>

<% if logged_in? %>
  <h4>Add Comment</h4>

  <% if flash[:comment_errors] %>
    <% flash[:comment_errors].each do |error| %>
      <%= error %>
    <% end %>
  <% end %>

  <%= form_for [@hack, @comment] do |f| %>
      <div>
        <%= f.text_area :content %>
      </div>
      <div>
        <%= f.hidden_field :user_id, :value => @user.id %>
        <%= f.hidden_field :hack_id, :value => @hack.id %>
      </div>
        
      <%= f.submit "Submit", class: "btn btn-outline-success btn-sm" %>
    <% end %>
<% end %>