config/routes.rb
Rails.application.routes.draw do
  resources :destinations, only: [:index, :show] do 
    resources :hacks, shallow: true do
      resources :comments, shallow: true
      resources :likes, shallow: true
    end  
  end
  resources :users, only: [:show, :edit, :update, :destroy] do
    resources :follows, shallow: true
  end
  resources :sessions, only: [:new, :create, :destroy]

  get '/signup', to: 'users#new', as: 'signup'
  post '/signup', to: 'users#create', as: 'users'
  get '/login', to: 'sessions#new', as: 'login'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  get '/search-results', to: 'search#search' 
  root 'welcome#welcome'

end

app/models/user.rb
class User < ApplicationRecord
  has_many :hacks, dependent: :destroy
  has_many :destinations, through: :hacks
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :active_relationships, class_name: "Follow", foreign_key: "follower_id", dependent: :destroy
  has_many :passive_relationships, class_name: "Follow", foreign_key: "followed_id", dependent: :destroy
  has_many :followed_users, through: :active_relationships, source: :followed_users
  has_many :follower_users, through: :passive_relationships, source: :follower_users
  validates :birthdate, presence: true
  validates :username, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :bio, presence: true
  validates :password, length: { in: 8..20 }
  validate :age_greater_or_equal_to_13
  has_secure_password

  def age_greater_or_equal_to_13
    if birthdate
      if self.age < 13
        errors.add(:birthdate, ": Must be 13 or older")
      elsif self.age > 130
        errors.add(:birthdate, ": Troll Detected")
      end
    end
  end

  def age
    bday = birthdate.strftime("%d-%m-%Y")
    ((Time.zone.now - bday.to_time) / 1.year.seconds).floor
  end

  def top_five
    hacks.joins(:likes).select('hacks.*, count(hack_id) as hcount').group('hack_id').order('hcount DESC').limit(5)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, only: [:show, :edit, :update, :destroy]
  before_action :require_login, except:[:new, :create, :show]

  def show
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    if @user.valid?
      session[:user_id] = @user.id
      redirect_to @user
    else
      flash[:errors] = @user.errors.full_messages
      render 'new' 
    end
  end

  def edit
   
  end

  def update
    @user.update(user_params)
    if @user.valid?
      redirect_to @user
    else
      flash.now[:errors] = @user.errors.full_messages
      render 'edit'
    end 
  end

  def destroy
    session.clear
    @user.destroy
    redirect_to root_path
  end

  private

  def find_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :birthdate, :email, :location, :bio, :username, :password, :password_confirmation)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<% if flash[:errors] %>
  <%= "Please Fix Errors and Try Again" %>
  <br>
  <% flash[:errors].each do |error| %>
    <div>
    <%= error %>
    </div>
  <% end %>
<% end %>
<br>

<%= form_for @user do |f| %>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label :birthdate %>
    <%= f.date_field :birthdate %>
  </div>
  <div>
    <%= f.label :location %>
    <%= f.text_field :location %>
  </div>
  <div>
    <%= f.label :bio %>
    <%= f.text_area :bio %>
  </div>
  <div>
    <div>
      <%= f.label :username %>
      <%= f.text_field :username %>
    </div>
    <div>
      <%= f.label :email %>
      <%= f.text_field :email %>
    </div>
    <div>
      <%= f.label :password %>
      <%= f.password_field :password %>
    </div>
    <div>
      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation %>
    </div>
  <%= f.submit class: "btn btn-outline-success btn-sm" %>
<% end %>

app/views/users/edit.html.erb
<h2>Edit Account Settings</h2>

<%= render 'form' %>

 <%= button_to "Delete Profile", user_path(@user), method: :delete, class: "btn btn-outline-danger btn-sm" %>

app/views/users/new.html.erb
<h1>Create Account</h1>


<%= render 'form' %>

app/views/users/show.html.erb
<h1><%= @user.name %></h1>
<% if logged_in? %>
  <%= button_to "#{@user.passive_relationships.count} Followers", user_follows_path(@user), params: {relationship: "Followers"}, :method => :get, class: "btn btn-outline-info btn-sm" %>
  <%= button_to "#{@user.active_relationships.count} Following", user_follows_path(@user), params: {relationship: "Following"}, :method => :get, class: "btn btn-outline-info btn-sm" %>
<% end %>
<br>
<%= "Username: #{@user.username}" %>
<br>
<%= "Location: #{@user.location}" %>
<br>
<%= "Bio: #{@user.bio}" %>
<br>
<%= "Age: #{@user.age}" %>
<br>

<% if logged_in? && current_user == @user %>
  <%= button_to "Edit Profile", edit_user_path, method: :get, class: "btn btn-outline-primary btn-sm" %>
<% end %>


<% if logged_in? && current_user != @user %>
  <% pre_follow = @user.passive_relationships.find_by(follower_id: current_user.id) %>
  <% if pre_follow %>
    <%= button_to "Followed", follow_path(pre_follow), :method => :delete, class: "btn btn-outline-success btn-sm" %>
  <% else %>
    <%= button_to "Follow", user_follows_path(@user), :method => :post, class: "btn btn-outline-primary btn-sm" %>
  <% end %>
<% end %>

<br>
<h4><%= @user.name %>'s Top Hacks</h4>
<% @user.top_five.each do |hack| %>
  <p><%= link_to hack.title, hack %>, <%= hack.destination.str_addr_fields %>, <%= hack.likes.count %> Likes</p>
<% end %>

<br>
<h4><%= @user.name %>'s Hacks</h4>
<% @user.hacks.each do |hack| %>
  <p><%= link_to hack.title, hack %>, <%= hack.destination.str_addr_fields %></p>
<% end %>