config/routes.rb
Rails.application.routes.draw do
  resources :destinations, only: [:index, :show] do 
    resources :hacks, shallow: true do
      resources :comments, shallow: true
      resources :likes, shallow: true
    end  
  end
  resources :users, only: [:show, :edit, :update, :destroy] do
    resources :follows, shallow: true
  end
  resources :sessions, only: [:new, :create, :destroy]

  get '/signup', to: 'users#new', as: 'signup'
  post '/signup', to: 'users#create', as: 'users'
  get '/login', to: 'sessions#new', as: 'login'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  get '/search-results', to: 'search#search' 
  root 'welcome#welcome'

end

app/models/destination.rb
class Destination < ApplicationRecord
  has_many :hacks
  has_many :users, through: :hacks
  has_many :likes, through: :hacks
  has_many :comments, through: :hacks

  def str_addr_fields
    str = "#{self.city}"
    str << ", #{self.state}" if self.state.present?
    str << ", #{self.country}" unless self.country == 'USA' ||  self.country == nil
    str
  end

  # def self.search(search)
  #   if search
  #     destinations = Destination.where("city LIKE (?) OR state LIKE (?) OR country LIKE (?)", "%#{search}%", "%#{search}%", "%#{search}%")
  #   else
  #     Destination.all
  #   end
  # end

  def category_hacks(cat)
    Hack.where(category: cat, destination: self)
  end

  def five_recent
    self.hacks.select('hacks.*').order('created_at DESC').limit(5)
  end
end

app/controllers/destinations_controller.rb
class DestinationsController < ApplicationController
  before_action :find_destination, only: [:show]
  before_action :categories, only: :show
  
  def index
    @destinations = Destination.all
  end

  def show
    @hack = Hack.new
  end

  private

  def find_destination
    @destination = Destination.find(params[:id])
  end

  def categories
    @categories = ["Transportation", "Dining", "Nightlife", "Cultural", "Adventure", "Rewards/Points"]
  end
end

app/helpers/destinations_helper.rb
module DestinationsHelper
end

app/views/destinations/index.html.erb
<h1>Destinations</h1>

<% @destinations.sort_by {|destination| destination.city }.each do |destination| %>
  
  <%= link_to destination.str_addr_fields, destination %>
  
  <% if false %>
  <br>
  <a href= "/destinations/<%= destination.id %>"><img src="<%= destination.img_url %>" class="small-img" ></a>
  <% end %>

  <% if false %>
  <div class="card" style="width: 18rem;">
    <img class="card-img-top" src="<%= destination.img_url %>" alt="Card image cap">
    <div class="card-body">
      <h5 class="card-title"><%= destination.str_addr_fields %></h5>
      <p class="card-text">See <%= destination.city %> Hacks!</p>
      <a href="/destinations/<%= destination.id %>" class="btn btn-primary">Select</a>
    </div>
  </div>
  <% end %>
  
  <br>
<% end %>

app/views/destinations/show.html.erb
<h1><%= @destination.str_addr_fields %></h1>

<img src="<%= @destination.img_url %>" class="reg-img">

<br>


<% if logged_in? %>
  <%= button_to "Add a New Travel Hack", new_destination_hack_path(params[:id]), :method => :get, class: "btn btn-outline-primary btn-sm" %>
<% end %>

<%= button_to "See All Hacks", destination_hacks_path(params[:id]), :method => :get, class: "btn btn-outline-primary btn-sm" %>

<br>

<div class="container">
  <div class="row">
    <div class="col-sm">
      <%= link_to "Adventure", destination_hacks_path(@destination, params: {:cat => "Adventure", :destination_id => @destination.id}) %>
    </div>
    <div class="col-sm">
      <%= link_to "Cultural", destination_hacks_path(@destination, params: {:cat => "Cultural", :destination_id => @destination.id}) %>
    </div>
    <div class="col-sm">
      <%= link_to "Dining", destination_hacks_path(@destination, params: {:cat => "Dining", :destination_id => @destination.id}) %>
    </div>
    <div class="col-sm">
      <%= link_to "Nightlife", destination_hacks_path(@destination, params: {:cat => "Nightlife", :destination_id => @destination.id}) %>
    </div>
    <div class="col-sm">
      <%= link_to "Rewards/Points", destination_hacks_path(@destination, params: {:cat => "Rewards/Points", :destination_id => @destination.id}) %>
    </div>
    <div class="col-sm">
     <%= link_to "Transportation", destination_hacks_path(@destination, params: {:cat => "Transportation", :destination_id => @destination.id}) %>
    </div>
  </div>
</div>



<br>
<h3>Recent <%= @destination.city %> Hacks</h3>
<% @destination.five_recent.each do |hack| %>
  <h4><%= link_to hack.title, hack %></h4>
  <p><%= hack.category %></p>
  <p><%= hack.created_at.strftime("%m/%d/%Y") %></p>
  <p><%= hack.content %></p>
  <p>Submitted by <%= hack.user.name %></p>
  <br>
<% end %>


  