config/routes.rb
Rails.application.routes.draw do
  resources :destinations, only: [:index, :show] do 
    resources :hacks, shallow: true do
      resources :comments, shallow: true
      resources :likes, shallow: true
    end  
  end
  resources :users, only: [:show, :edit, :update, :destroy] do
    resources :follows, shallow: true
  end
  resources :sessions, only: [:new, :create, :destroy]

  get '/signup', to: 'users#new', as: 'signup'
  post '/signup', to: 'users#create', as: 'users'
  get '/login', to: 'sessions#new', as: 'login'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  get '/search-results', to: 'search#search' 
  root 'welcome#welcome'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :hack
end

app/models/destination.rb
class Destination < ApplicationRecord
  has_many :hacks
  has_many :users, through: :hacks
  has_many :likes, through: :hacks
  has_many :comments, through: :hacks

  def str_addr_fields
    str = "#{self.city}"
    str << ", #{self.state}" if self.state.present?
    str << ", #{self.country}" unless self.country == 'USA' ||  self.country == nil
    str
  end

  # def self.search(search)
  #   if search
  #     destinations = Destination.where("city LIKE (?) OR state LIKE (?) OR country LIKE (?)", "%#{search}%", "%#{search}%", "%#{search}%")
  #   else
  #     Destination.all
  #   end
  # end

  def category_hacks(cat)
    Hack.where(category: cat, destination: self)
  end

  def five_recent
    self.hacks.select('hacks.*').order('created_at DESC').limit(5)
  end
end

app/models/follow.rb
class Follow < ApplicationRecord
    belongs_to :followed_user, class_name: "User", foreign_key: :followed_id
    belongs_to :follower_user, class_name: "User", foreign_key: :follower_id
end

app/models/hack.rb
class Hack < ApplicationRecord
  belongs_to :user
  belongs_to :destination
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  validates :title, presence: true
  validates :content, presence: true
  

  def category_hacks(cat)
    Hack.where(category: cat)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :hack
end

app/models/user.rb
class User < ApplicationRecord
  has_many :hacks, dependent: :destroy
  has_many :destinations, through: :hacks
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :active_relationships, class_name: "Follow", foreign_key: "follower_id", dependent: :destroy
  has_many :passive_relationships, class_name: "Follow", foreign_key: "followed_id", dependent: :destroy
  has_many :followed_users, through: :active_relationships, source: :followed_users
  has_many :follower_users, through: :passive_relationships, source: :follower_users
  validates :birthdate, presence: true
  validates :username, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :bio, presence: true
  validates :password, length: { in: 8..20 }
  validate :age_greater_or_equal_to_13
  has_secure_password

  def age_greater_or_equal_to_13
    if birthdate
      if self.age < 13
        errors.add(:birthdate, ": Must be 13 or older")
      elsif self.age > 130
        errors.add(:birthdate, ": Troll Detected")
      end
    end
  end

  def age
    bday = birthdate.strftime("%d-%m-%Y")
    ((Time.zone.now - bday.to_time) / 1.year.seconds).floor
  end

  def top_five
    hacks.joins(:likes).select('hacks.*, count(hack_id) as hcount').group('hack_id').order('hcount DESC').limit(5)
  end
end

app/controllers/hacks_controller.rb
class HacksController < ApplicationController
    before_action :find_hack, only: [:show, :edit, :update, :destroy]
    before_action :categories, only: [:new, :edit]
    before_action :require_login, only: [:new, :create, :edit, :update, :destroy]


  def index
    @destination = Destination.find(params[:destination_id])
    @category = params[:cat]
  end

  def show
    @comment = Comment.new
    if current_user
      @user = User.find(current_user.id)
    end
  end


  def new
    
    @hack = Hack.new
    @destination = Destination.find(params[:destination_id])
    @dest_city = @destination.city
    @user = User.find(session[:user_id])
  end

  def create
    @hack = Hack.create(hack_params)   
    if @hack.valid?
      redirect_to hack_path(id: @hack)
    else
      flash[:errors] = @hack.errors.full_messages
      redirect_to new_destination_hack_path(params[:destination_id]) 
    end
  end

  def edit
    @dest_city = @hack.destination.city
    @user = User.find(session[:user_id])
    
  end

  def update
    @hack.update(hack_params)
    if @hack.valid?
      redirect_to hack_path(id: @hack)
    else
      flash[:errors] = @hack.errors.full_messages
      redirect_to edit_hack_path
    end 
  end

  def destroy
    @hack.destroy
    redirect_to destinations_path
  end

  private

  def find_hack
    @hack = Hack.find(params[:id])
  end

  def hack_params
    params.require(:hack).permit(:category, :title, :content, :user_id, :destination_id)
  end

  def categories
    @categories = ["Transportation", "Dining", "Nightlife", "Cultural", "Adventure", "Rewards/Points"]
  end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :find_like, only: [:destroy]
  
  def create

    if already_liked?
      flash[:notice] = "You can't like more than once"
    else
      like = Like.create(like_params)
      redirect_to hack_path(like.hack_id)
    end
  end

  def destroy
    if !(already_liked?)
      flash[:notice] = "Cannot unlike"
    else
      @like.destroy
    end
    redirect_to hack_path(@like.hack_id)
  end

  private

  def already_liked?
    Like.where(user_id: current_user.id, hack_id: params[:id]).exists?
  end

  def find_like
    @like = Like.find_by(user_id: current_user.id, hack_id: params[:id])
  end

  def like_params
    params.require(:like).permit(:user_id, :hack_id)
  end
  
end

app/controllers/search_controller.rb
class SearchController < ApplicationController

    def search
        @results = all_search(params[:search])
      end

    def all_search(search)
        if search
            results = [[],[],[]]
            results[0] = Destination.where("city LIKE (?) OR state LIKE (?) OR country LIKE (?)", "%#{search}%", "%#{search}%", "%#{search}%")
            results[1] = Hack.where("title LIKE (?) OR content LIKE (?)", "%#{search}%", "%#{search}%")
            results[2] = User.where("name LIKE (?) OR username LIKE (?)", "%#{search}%", "%#{search}%")
            results
        else
            redirect_to root_path
        end
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, only: [:show, :edit, :update, :destroy]
  before_action :require_login, except:[:new, :create, :show]

  def show
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    if @user.valid?
      session[:user_id] = @user.id
      redirect_to @user
    else
      flash[:errors] = @user.errors.full_messages
      render 'new' 
    end
  end

  def edit
   
  end

  def update
    @user.update(user_params)
    if @user.valid?
      redirect_to @user
    else
      flash.now[:errors] = @user.errors.full_messages
      render 'edit'
    end 
  end

  def destroy
    session.clear
    @user.destroy
    redirect_to root_path
  end

  private

  def find_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :birthdate, :email, :location, :bio, :username, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cat_helper.rb
module CatHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/destinations_helper.rb
module DestinationsHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/hacks_helper.rb
module HacksHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Travel Hack</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">Travel Hack</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/">Home<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/destinations">Destinations</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Account
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <% if logged_in? %>
            <a class="dropdown-item" href="/users/<%= "#{current_user.id}" %>" method: :get>My Profile</a>
            <a class="dropdown-item" href="/logout" method: :post>Logout</a>
          <% else %>
            <a class="dropdown-item" href="/login" method: :get>Login</a>
            <a class="dropdown-item" href="/signup" method: :get>Create Account</a>
          <% end %>
        </div>
      </li>
    </ul>

  <%= form_tag(search_results_path, method: :get, class: 'form-inline my-2 my-lg-0') do %>
      <%= text_field_tag(:search, params[:search], class: 'form-control mr-sm-2', placeholder: "Search") %>
      <%= submit_tag("Search", class: "btn btn-outline-success my-2 my-sm-0") %>
  <% end %>


    
  </div>
</nav>
    <main>
    <%= yield %>
    </main>
  </body>
</html>